"""
Tools :: Utils Layer
====================

Shared, dependency-free primitives used by every other Tools package:
identifiers, hashing, caching, configuration, path safety, helpers,
serialization and validation.

The Utils layer has no knowledge of any domain concept (tool, adapter,
blockchain, AI ...).  It exists so that higher layers never hand-roll
crypto, path checks, or validation logic inconsistently.
"""

from __future__ import annotations

from .cache import CacheStats, LRUCache, TTLCache, timed_lru_cache
from .config import Config, flatten_env, load_config, read_json_file, read_toml_file
from .hashing import (
    checksum,
    constant_time_compare,
    deterministic_key,
    fingerprint,
    hash_bytes,
    hash_file,
    hash_struct,
    hash_text,
    new_hmac,
    verify_checksum,
)
from .helpers import (
    Timer,
    chunked,
    deep_get,
    deep_merge,
    deep_set,
    elapsed_ms,
    iso_now,
    mask_secret,
    now_utc,
    redact,
    safe_dump,
    to_dict,
    to_slug,
    truncate,
    unique,
)
from .ids import (
    fingerprint as id_fingerprint,
    is_id,
    new_hex_id,
    new_id,
    new_name_id,
    new_short_id,
    new_trace_id,
    slugify,
)
from .paths import (
    atomic_write,
    can_inside,
    ensure_dir,
    list_dirs,
    list_files,
    normalize,
    safe_filename,
    safe_join,
    temp_directory,
)
from .serialization import (
    from_base64,
    from_json,
    is_serializable,
    to_base64,
    to_json,
    to_json_bytes,
    to_json_compact,
)
from .validation import (
    ValidationError,
    ValidationResult,
    ensure_string,
    ensure_type,
    in_enum,
    in_range,
    is_truthy,
    matches,
    max_length,
    min_length,
    of_type,
    optional,
    required,
    validate,
    validate_dict,
)

__all__ = [
    "Timer",
    "CacheStats",
    "LRUCache",
    "TTLCache",
    "timed_lru_cache",
    "Config",
    "flatten_env",
    "load_config",
    "read_json_file",
    "read_toml_file",
    "checksum",
    "constant_time_compare",
    "deterministic_key",
    "fingerprint",
    "hash_bytes",
    "hash_file",
    "hash_struct",
    "hash_text",
    "new_hmac",
    "verify_checksum",
    "deep_get",
    "deep_merge",
    "deep_set",
    "elapsed_ms",
    "iso_now",
    "mask_secret",
    "now_utc",
    "redact",
    "safe_dump",
    "to_dict",
    "to_slug",
    "truncate",
    "unique",
    "is_id",
    "new_hex_id",
    "new_id",
    "new_name_id",
    "new_short_id",
    "new_trace_id",
    "slugify",
    "atomic_write",
    "can_inside",
    "ensure_dir",
    "list_dirs",
    "list_files",
    "normalize",
    "safe_filename",
    "safe_join",
    "temp_directory",
    "from_base64",
    "to_base64",
    "from_json",
    "is_serializable",
    "to_json",
    "to_json_bytes",
    "to_json_compact",
    "ValidationError",
    "ValidationResult",
    "in_enum",
    "in_range",
    "is_truthy",
    "matches",
    "max_length",
    "min_length",
    "of_type",
    "optional",
    "required",
    "validate",
    "validate_dict",
    "ensure_string",
    "ensure_type",
]