"""
CIE-OS
A01 Blockchain Intelligence Agent

Module:
    tools.placement

Purpose:
    Say, for every directory that holds no code, where that concept is actually
    implemented -- or what its implementation is waiting on.

Design goals:
    - One table; the 143 READMEs are generated, never hand-maintained
    - Every pointer's target verified to exist, so a rename fails a test
    - `planned` reasons sourced from the registry that already holds them
    - Deterministic output; regenerating an unchanged tree changes nothing
    - No package imports at module load, so this stays runnable in a broken tree

Notes:
    A01's scaffolding names concepts it has not built, and names several it
    *has* built in a second place. ``blockchain/decoding/events/`` is empty
    because event decoding lives in ``contracts/``; ``api/`` is empty because
    the HTTP surface is ``interfaces/rest.py``. Both are correct. What is not
    correct is leaving the empty directory unexplained --
    ``docs/architecture/folder-architecture.md`` §10 puts it exactly:

        "an empty directory named ``security/`` invites code to be written in
        the wrong place."

    So each empty directory gets a short README naming its canonical home. The
    alternative the architecture doc recommends -- deleting them -- also works,
    but loses the roadmap the tree encodes, and the operator wants that kept.

    **The pointers are generated, and that is the point.** 143 hand-written
    notes would be 143 future lies: the first rename makes one wrong, and
    nothing catches it. Here the table is the single source, and
    :func:`verify` asserts every target still exists -- so a rename breaks a
    test instead of quietly stranding a reader.

    ``planned`` reasons are read from :data:`skills.registry.PLANNED_SKILLS`
    rather than restated. Two lists of "why this is not built yet" drift, and
    the drift is invisible.
"""

from __future__ import annotations

import fnmatch

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Final, Iterable

#: Repository root, derived from this file rather than assumed. The agent is
#: checked out at different depths in different layouts.
ROOT: Final[Path] = Path(__file__).resolve().parent.parent

#: Marker on every generated file, so a human edit is distinguishable and a
#: regeneration knows what it may overwrite.
GENERATED_MARKER: Final[str] = "<!-- generated by tools/placement.py -->"

#: Directories that are not part of the agent and are never scanned.
SKIP_PARTS: Final[frozenset[str]] = frozenset(
    {"__pycache__", ".git", ".pytest_cache", ".venv", "node_modules", "data", "logs"}
)


class State(StrEnum):
    """Why a directory is empty."""

    #: The concept is built, at a different path. Do not write it here.
    IMPLEMENTED = "implemented"
    #: Not built. The reason is a missing capability, named.
    PLANNED = "planned"
    #: Deliberately empty, and must stay that way.
    NEVER = "never"


@dataclass(frozen=True, slots=True)
class Placement:
    """One rule covering a directory or a glob of them."""

    pattern: str
    state: State
    #: Repo-relative path of the real implementation. Required for IMPLEMENTED,
    #: verified to exist.
    target: str = ""
    #: One line: what this slot is for, and why it is where it is.
    note: str = ""

    def matches(self, relative: str) -> bool:
        return fnmatch.fnmatch(relative, self.pattern)


# ==============================================================================
# THE TABLE
# ==============================================================================
#
# Ordered most specific first; the first match wins. Every `target` is checked
# by verify(), so a moved module fails the suite rather than stranding a reader.

PLACEMENT: Final[tuple[Placement, ...]] = (
    # -- deliberately empty ---------------------------------------------------
    Placement(
        "sandbox",
        State.NEVER,
        note=(
            "Experimental scratch space. README.md declares it never shipped "
            "and never imported, and a test enforces that nothing imports from "
            "it. Code placed here would be shipped by accident."
        ),
    ),
    # -- top-level duplicates of a layer package ------------------------------
    #
    # These eight are gone from the table because they stopped being empty.
    # `api/`, `monitoring/`, `models/`, `plugins/`, `reasoning/`,
    # `reporting/`, `security/` and `workflows/` are now redirect packages:
    # each binds the canonical module object itself and forwards every other
    # name to it live, so `api.rest is interfaces.rest`.
    #
    # That is the same claim their generated READMEs used to make, moved
    # somewhere the interpreter checks it. A rename now breaks an import
    # rather than stranding a reader, and `tools/security/tests` asserts the
    # identity so a future re-implementation inside one of those directories
    # fails a test instead of quietly becoming a second copy.
    #
    # `sandbox/` stays in the table above, and stays empty. It is the one
    # directory where a redirect would be wrong: there is nothing to redirect
    # to, and code placed there ships by accident.
    #
    # `security/retrieval/` keeps its pointer, and is the one case where the
    # redirect treatment would mislead. Its target is `memory/retrieval` --
    # retrieval filtering and ranking, which is not a security control at all.
    # Binding it as `security.retrieval` would assert a relationship the code
    # does not have; the note says where the concept lives and stops there.
    Placement(
        "security/retrieval",
        State.IMPLEMENTED,
        "memory/retrieval",
        "Retrieval filtering and ranking.",
    ),
    # -- filled by this change ------------------------------------------------
    Placement(
        "knowledge",
        State.IMPLEMENTED,
        "knowledge/chains.py",
        "What A01 can and cannot learn about each registered chain.",
    ),
    Placement(
        "examples",
        State.IMPLEMENTED,
        "examples/README.md",
        "Runnable, offline walkthroughs driven by recorded fixtures.",
    ),
    Placement(
        "assets",
        State.IMPLEMENTED,
        "assets/pipeline.svg",
        "Architecture diagrams. Self-contained SVG, no external references.",
    ),
    # -- blockchain/ scaffolding ----------------------------------------------
    Placement(
        "blockchain/decoding/*",
        State.IMPLEMENTED,
        "contracts/events.py",
        (
            "Event and calldata decoding. ERC-20 and ERC-721 share a topic0, so "
            "identity comes from log shape -- see contracts/signatures.py."
        ),
    ),
    Placement(
        "blockchain/entities/*",
        State.IMPLEMENTED,
        "schemas",
        (
            "Canonical block, transaction, token and NFT records, with exact "
            "256-bit amounts and case-folded addresses."
        ),
    ),
    Placement(
        "blockchain/analytics/*",
        State.IMPLEMENTED,
        "database/analytics.py",
        (
            "Aggregate reads over stored history. Every figure carries the "
            "window it was computed over."
        ),
    ),
    Placement(
        "blockchain/chains/*",
        State.IMPLEMENTED,
        "config/rpc/chains.py",
        (
            "Per-chain metadata is one registry, not one module per chain. "
            "What A01 can do on each is knowledge/chains.py."
        ),
    ),
    Placement(
        "blockchain/adapters/*",
        State.IMPLEMENTED,
        "blockchain/rpc/providers/catalog.py",
        "Provider endpoints and access tiers; transports are tools/adapters.",
    ),
    Placement(
        "blockchain/flows/*",
        State.IMPLEMENTED,
        "skills/token_flow/flow.py",
        (
            "Value flow, native and per-token. Kept per contract because raw "
            "token amounts are not comparable across tokens."
        ),
    ),
    Placement(
        "blockchain/ingestion/*",
        State.IMPLEMENTED,
        "ingestion",
        "Reorg-safe head polling, checkpoints, dedup, bounded queue, backfill.",
    ),
    Placement(
        "blockchain/indexing/*",
        State.IMPLEMENTED,
        "database/repositories.py",
        (
            "Indexes are declared with the schema in database/migrations.py; "
            "every one is justified by a query the system issues."
        ),
    ),
    Placement(
        "blockchain/storage/*",
        State.IMPLEMENTED,
        "database/connection.py",
        (
            "SQLite system of record. Withdrawn blocks are retained, so reads "
            "exclude them by default rather than deleting history."
        ),
    ),
    Placement(
        "blockchain/reorg/*",
        State.IMPLEMENTED,
        "blockchain/reorg/detector.py",
        (
            "Already a module beside this directory: detector.py and "
            "finality.py. The empty subdirectory is scaffolding."
        ),
    ),
    Placement(
        "blockchain/rpc/*",
        State.IMPLEMENTED,
        "config/rpc/fallback.py",
        (
            "Failover and health tracking sit with the RPC registry; dispatch "
            "and rate limiting are blockchain/rpc/clients."
        ),
    ),
    Placement(
        "blockchain/validation/*",
        State.IMPLEMENTED,
        "normalization/evm.py",
        (
            "Validation refuses; quality annotates. A payload that cannot state "
            "which block it is gets rejected whole, never defaulted."
        ),
    ),
    Placement(
        "blockchain/monitoring/*",
        State.IMPLEMENTED,
        "telemetry/metrics.py",
        "Ingestion counters, lag and data-quality gauges.",
    ),
    # `exploit_detection` and `approval_risk` are built and are therefore not
    # listed: this table covers directories with no code. What is left under
    # `blockchain/security/` still needs contract bytecode analysis, which is
    # a narrower blocker than the one this entry used to state -- the original
    # wording also blamed "event decoding beyond transfers", and `contracts/`
    # has decoded Approval and ApprovalForAll since the contracts layer landed.
    Placement(
        "blockchain/security/*",
        State.PLANNED,
        note=(
            "Contract-level screening: rug-pull indicators, vulnerability "
            "surface, RPC-provider behaviour. Needs contract bytecode "
            "analysis and an ABI source, neither of which A01 ingests -- "
            "`contracts/` reads logs by shape and cannot read what a contract "
            "is able to do. Specs in docs/intelligence/detection-catalog.md."
        ),
    ),
    Placement(
        "blockchain/labeling/*",
        State.PLANNED,
        note=(
            "Entity, exchange and contract labels. A01 ingests no label source, "
            "which is why exchange-flow direction and USD floors are "
            "unavailable today."
        ),
    ),
    Placement(
        "blockchain/nodes/*",
        State.PLANNED,
        note=(
            "Node-tier awareness. Measured on every registered chain, the free "
            "endpoints report archive: no -- so historical state is out of "
            "reach until a keyed provider is configured."
        ),
    ),
    # -- intelligence/ engine stubs -------------------------------------------
    Placement(
        "intelligence/confidence_engine",
        State.IMPLEMENTED,
        "intelligence/evidence/confidence.py",
        "Confidence scoring over the evidence chain.",
    ),
    Placement(
        "intelligence/reasoning_engine",
        State.IMPLEMENTED,
        "intelligence/reasoning",
        "Reasoning strategies.",
    ),
    Placement(
        "intelligence/risk_engine",
        State.IMPLEMENTED,
        "decision/engine.py",
        (
            "Scoring, ranking and the maturity gate. Severity is discounted by "
            "confidence rather than averaged with it."
        ),
    ),
    Placement(
        "intelligence/anomaly_engine",
        State.IMPLEMENTED,
        "intelligence/scoring",
        "Anomaly and outlier scoring.",
    ),
    Placement(
        "intelligence/behavior_engine",
        State.IMPLEMENTED,
        "intelligence/analysis/wallet.py",
        "Wallet behaviour analysis; composition is intelligence/engines.",
    ),
    Placement(
        "intelligence/liquidity_engine",
        State.IMPLEMENTED,
        "intelligence/analysis/liquidity.py",
        "Liquidity analysis.",
    ),
    Placement(
        "intelligence/probability_engine",
        State.IMPLEMENTED,
        "evaluation/metrics.py",
        (
            "Base rates and calibration. Precision alone is misleading without "
            "the posterior a base rate implies."
        ),
    ),
    Placement(
        "intelligence/manipulation_engine",
        State.PLANNED,
        note=(
            "MEV, sandwich and wash-trading detection. Specified as DET-MEV-01 "
            "and DET-ARB-01; needs mempool access, and public-mempool coverage "
            "is shrinking as extraction moves to private relays."
        ),
    ),
    Placement(
        "intelligence/digital_twin",
        State.PLANNED,
        note=(
            "Simulated chain state for counterfactuals. capabilities.md §11 "
            "excludes it from v1 deliberately."
        ),
    ),
    Placement(
        "intelligence/blockchain_dna",
        State.PLANNED,
        note=(
            "Behavioural fingerprinting. capabilities.md §11 excludes it from "
            "v1 deliberately."
        ),
    ),
    # -- skills/ ---------------------------------------------------------------
    # Reason text comes from skills.registry.PLANNED_SKILLS at generation time,
    # so the two cannot drift.
    Placement(
        "skills/*",
        State.PLANNED,
        note="",
    ),
)


# ==============================================================================
# SCANNING
# ==============================================================================


def is_empty(directory: Path) -> bool:
    """
    True when a directory holds no content of its own.

    ``.gitkeep`` and a generated README do not count: the first exists only to
    make git track the directory, and the second is what this module writes.
    Counting either would make the scan report success the moment it ran once.
    """
    for child in directory.iterdir():
        if child.is_dir():
            return False
        if child.name == ".gitkeep":
            continue
        if child.name == "README.md" and GENERATED_MARKER in _read(child):
            continue
        return False
    return True


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def empty_directories(root: Path | None = None) -> tuple[Path, ...]:
    """Every directory in the tree with no content of its own."""
    base = root or ROOT
    found: list[Path] = []
    for directory in base.rglob("*"):
        if not directory.is_dir():
            continue
        if SKIP_PARTS & set(directory.relative_to(base).parts):
            continue
        if is_empty(directory):
            found.append(directory)
    return tuple(sorted(found))


def relative(path: Path, root: Path | None = None) -> str:
    return path.relative_to(root or ROOT).as_posix()


def generated_orphans(root: Path | None = None) -> tuple[Path, ...]:
    """
    Generated READMEs left behind in directories that have since gained code.

    The failure this catches runs the opposite way from a stale pointer. A
    pointer rots when its *target* moves; an orphan rots when the directory
    itself fills in. ``skills/smart_money/`` was empty and said "Not built
    yet"; the skill was then built and the note stayed, so the directory
    shipped working code under a file denying it existed.

    Neither :func:`generate` nor :func:`verify` could see it: both walk
    :func:`empty_directories`, and the directory had stopped being empty --
    the moment it stopped being scanned is the moment it started lying.
    """
    base = root or ROOT
    found: list[Path] = []
    for directory in base.rglob("*"):
        if not directory.is_dir():
            continue
        if SKIP_PARTS & set(directory.relative_to(base).parts):
            continue
        if is_empty(directory):
            continue
        readme = directory / "README.md"
        if readme.is_file() and GENERATED_MARKER in _read(readme):
            found.append(readme)
    return tuple(sorted(found))


def resolve(relative_path: str) -> Placement | None:
    """The rule covering a directory, or None when the table has no answer."""
    for entry in PLACEMENT:
        if entry.matches(relative_path):
            return entry
    return None


# ==============================================================================
# PLANNED REASONS
# ==============================================================================


def planned_reasons() -> dict[str, str]:
    """
    Why each unbuilt skill is unbuilt, from the registry that already says so.

    Imported lazily: this module must stay runnable when the package tree is
    mid-edit, which is exactly when someone regenerates placement.
    """
    try:
        from skills.registry import PLANNED_SKILLS

        return dict(PLANNED_SKILLS)
    except Exception:  # noqa: BLE001 - tooling must survive a broken import
        return {}


# ==============================================================================
# GENERATION
# ==============================================================================


def render(relative_path: str, entry: Placement, reasons: dict[str, str]) -> str:
    """The README for one directory."""
    name = relative_path.rsplit("/", 1)[-1]
    lines = [GENERATED_MARKER, "", f"# `{relative_path}/`", ""]

    if entry.state is State.NEVER:
        lines += [
            "**Deliberately empty. Do not add code here.**",
            "",
            entry.note,
            "",
        ]
    elif entry.state is State.IMPLEMENTED:
        note = entry.note or "This concept is implemented elsewhere."
        lines += [
            f"**Implemented at [`{entry.target}`]({_link(relative_path, entry.target)}).**",
            "",
            note,
            "",
            "Do not add code here. A second implementation under this name would",
            "drift from the first, and nothing would report the divergence — see",
            "`docs/architecture/folder-architecture.md` §11.",
            "",
        ]
    else:
        reason = entry.note or reasons.get(name, "")
        lines += [
            "**Not built yet.**",
            "",
            (
                f"Blocked by: {reason}"
                if reason
                else "No implementation, and no blocking reason recorded."
            ),
            "",
            "The directory is kept because the structure is the roadmap. It will",
            "hold code once the capability above exists — not before, because a",
            "module that cannot do what its name claims is worse than an absence.",
            "",
        ]

    lines += [
        "---",
        "",
        "Regenerate with `python -m tools.placement --write`.",
        "",
    ]
    return "\n".join(lines)


def _link(from_dir: str, target: str) -> str:
    """A relative markdown link from the empty directory to its target."""
    depth = from_dir.count("/") + 1
    return "../" * depth + target


def generate(root: Path | None = None, *, write: bool = False) -> dict[str, str]:
    """
    Build a README for every empty directory.

    Returns the mapping of path to content. With ``write`` false nothing is
    touched, which is what the test uses to compare intent against the tree.
    """
    base = root or ROOT
    reasons = planned_reasons()
    produced: dict[str, str] = {}

    for directory in empty_directories(base):
        path = relative(directory, base)
        entry = resolve(path)
        if entry is None:
            continue
        content = render(path, entry, reasons)
        produced[path] = content
        if write:
            (directory / "README.md").write_text(content, encoding="utf-8")

    return produced


# ==============================================================================
# VERIFICATION
# ==============================================================================


@dataclass(frozen=True, slots=True)
class Report:
    """What verification found."""

    uncovered: tuple[str, ...] = ()
    missing_targets: tuple[tuple[str, str], ...] = ()
    unexplained: tuple[str, ...] = ()
    orphans: tuple[str, ...] = ()

    @property
    def ok(self) -> bool:
        return not (
            self.uncovered or self.missing_targets or self.unexplained or self.orphans
        )

    def describe(self) -> str:
        if self.ok:
            return "placement: every empty directory is covered and every target exists"
        parts: list[str] = []
        if self.uncovered:
            parts.append(
                f"{len(self.uncovered)} directory(ies) not covered by the table: "
                + ", ".join(self.uncovered[:5])
            )
        if self.missing_targets:
            parts.append(
                f"{len(self.missing_targets)} pointer(s) name a path that does not "
                "exist: " + ", ".join(f"{d} -> {t}" for d, t in self.missing_targets[:5])
            )
        if self.unexplained:
            parts.append(
                f"{len(self.unexplained)} planned directory(ies) with no reason: "
                + ", ".join(self.unexplained[:5])
            )
        if self.orphans:
            parts.append(
                f"{len(self.orphans)} generated README(s) describe a directory that "
                "now holds code: " + ", ".join(self.orphans[:5])
            )
        return "; ".join(parts)


def verify(root: Path | None = None) -> Report:
    """
    Check the table against the tree.

    Four failures matter, and two of them are the same failure seen from
    opposite ends: a pointer whose target was renamed, and a note left behind
    in a directory that has since been built. Both are READMEs that lie, and
    without this check nothing would ever notice either one.
    """
    base = root or ROOT
    reasons = planned_reasons()

    uncovered: list[str] = []
    missing: list[tuple[str, str]] = []
    unexplained: list[str] = []

    for directory in empty_directories(base):
        path = relative(directory, base)
        entry = resolve(path)

        if entry is None:
            uncovered.append(path)
            continue

        if entry.state is State.IMPLEMENTED:
            if not entry.target:
                missing.append((path, "<no target declared>"))
            elif not (base / entry.target).exists():
                missing.append((path, entry.target))

        if entry.state is State.PLANNED:
            name = path.rsplit("/", 1)[-1]
            if not entry.note and not reasons.get(name):
                unexplained.append(path)

    return Report(
        uncovered=tuple(uncovered),
        missing_targets=tuple(missing),
        unexplained=tuple(unexplained),
        orphans=tuple(relative(p, base) for p in generated_orphans(base)),
    )


def main(argv: Iterable[str] | None = None) -> int:
    """`python -m tools.placement [--write]`."""
    import sys

    args = list(argv if argv is not None else sys.argv[1:])
    write = "--write" in args

    report = verify()
    print(report.describe())

    produced = generate(write=write)
    verb = "wrote" if write else "would write"
    print(f"{verb} {len(produced)} README(s)")

    # An orphan is removed rather than rewritten: the table has no entry for a
    # directory that holds code, so there is nothing to regenerate it from.
    orphans = generated_orphans()
    if orphans:
        removed = "removed" if write else "would remove"
        print(f"{removed} {len(orphans)} orphaned README(s)")
        if write:
            for readme in orphans:
                readme.unlink()

    if not write:
        print("re-run with --write to apply")

    return 0 if (report.ok or write) else 1


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "GENERATED_MARKER",
    "PLACEMENT",
    "ROOT",
    "Placement",
    "Report",
    "State",
    "empty_directories",
    "generate",
    "generated_orphans",
    "is_empty",
    "planned_reasons",
    "resolve",
    "verify",
]
